gitRepoUrl = "https://github.com/morgann1/wally-packages"
gitSourceBranch = "main"

[[classOrder]]
section = "Modules"
classes = [
    "bindToInstanceDestroyed",
    "CharacterPromiseUtils",
    "disconnectAndClear",
    "input",
    "safePlayerAdded",
    "SimpleLogger",
    "TypeValidation",
    "WideLogger",
    "zzlib",
]

[[classOrder]]
section = "Cryo"
classes = ["Cryo", "Dictionary", "List"]

[[classOrder]]
section = "Plugin"
classes = [
    "doCleanup",
    "ElttobLog",
    "Event",
    "FinallyTask",
    "IconRamp",
    "Interposer",
    "IsLocalDev",
    "Leader",
    "Maybe",
    "OwnedToolbar",
    "PushPull",
    "SensationSounds",
    "SharedToolbar",
    "sortingBy",
    "ty",
]

[home]
enabled = true
includeReadme = false

[docusaurus]
tagline = "A collection of Roblox Luau modules for both plugin and game development."
