[package]
name = "morgann1/otter"
description = "Roblox Otter 1.3.7, vendored from Studio 0.716.0.7160873 via roblox-packages"
version = "1.3.7"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/morgann1/wally-packages"

[dependencies]
Collections = "roblox/luau-polyfill-collections@1.2.5"
Signal = "morgann1/signal@1.0.0"
