[package]
name = "morgann1/lumberyak"
description = "Roblox lumberyak 0.1.1, vendored from Studio 0.716.0.7160873 via roblox-packages"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/morgann1/wally-packages"

[dependencies]
Cryo = "morgann1/cryo@1.1.0"
