[package]
name = "morgann1/simple-logger"
description = "Simple logging utility"
version = "0.1.1"
license = "MIT"
authors = ["morgann1"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
