[package]
name = "morgann1/rbx-design-foundations"
description = "Roblox RbxDesignFoundations 2.0.163, vendored from Studio 0.716.0.7160873 via roblox-packages"
version = "2.0.163"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/morgann1/wally-packages"
