[package]
name = "morgann1/foundation-cloud-assets"
description = "Roblox FoundationCloudAssets 0.4.4, vendored from Studio 0.716.0.7160873 via roblox-packages"
version = "0.4.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/morgann1/wally-packages"
